
const properties = [
  {
    id: 1,
    title: "Modern 3-Bedroom Apartment",
    location: "Lekki Phase 1, Lagos",
    price: 85000000,
    type: "apartment",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 3,
    area: 185,
    image: "1.jpg",
    amenities: [
      "Parking",
      "24/7 Security",
      "Swimming Pool",
      "Gym",
    ],
    description:
      "A modern three-bedroom apartment in a secure residential development with contemporary interiors and excellent amenities.",
    agent: "Daniel Okafor",
  },

  {
    id: 2,
    title: "Luxury 4-Bedroom Duplex",
    location: "Ikoyi, Lagos",
    price: 1500000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 5,
    area: 420,
    image: "2.jpg",
    amenities: [
      "BQ",
      "Garage",
      "Garden",
      "Security",
      "CCTV",
    ],
    description:
      "Spacious luxury duplex featuring premium finishes, private parking and a beautifully landscaped outdoor area.",
    agent: "Amaka Williams",
  },

  {
    id: 3,
    title: "Cozy 2-Bedroom Apartment",
    location: "Yaba, Lagos",
    price: 3500000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    image: "3.jpg",
    amenities: [
      "Parking",
      "Security",
      "Prepaid Meter",
    ],
    description:
      "A comfortable two-bedroom apartment located close to major commercial areas, universities and public transportation.",
    agent: "Michael Adeyemi",
  },

  {
    id: 4,
    title: "Executive 5-Bedroom Duplex",
    location: "Maitama, Abuja",
    price: 2500000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 5,
    bathrooms: 6,
    area: 600,
    image: "4.jpg",
    amenities: [
      "Swimming Pool",
      "Gym",
      "BQ",
      "Garden",
      "Garage",
    ],
    description:
      "An elegant executive duplex designed for luxury family living in one of Abuja's premium residential districts.",
    agent: "Ibrahim Musa",
  },

  {
    id: 5,
    title: "Affordable 1-Bedroom Flat",
    location: "Bodija, Ibadan",
    price: 1200000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    image: "5.jpg",
    amenities: [
      "Parking",
      "Security",
      "Water Supply",
    ],
    description:
      "A neat and affordable one-bedroom apartment suitable for students and young professionals.",
    agent: "Tolu Adebayo",
  },

  {
    id: 6,
    title: "Contemporary 3-Bedroom Duplex",
    location: "Gwarinpa, Abuja",
    price: 75000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 4,
    area: 260,
    image: "6.jpg",
    amenities: [
      "Parking",
      "Garden",
      "Security",
      "BQ",
    ],
    description:
      "Contemporary duplex with spacious rooms, modern finishes and a private outdoor space.",

  },

  {
    id: 7,
    title: "Waterfront Luxury Apartment",
    location: "Victoria Island, Lagos",
    price: 180000000,
    type: "apartment",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 4,
    area: 220,
    image: "7.jpg",
    amenities: [
      "Waterfront View",
      "Pool",
      "Gym",
      "Parking",
      "Security",
    ],
    description:
      "Premium waterfront apartment offering beautiful views and resort-style residential amenities.",
    agent: "Sarah Johnson",
  },

  {
    id: 8,
    title: "Family 4-Bedroom Home",
    location: "Akobo, Ibadan",
    price: 65000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 4,
    area: 450,
    image: "8.jpg",
    amenities: [
      "Garden",
      "Parking",
      "Security",
      "BQ",
    ],
    description:
      "Spacious family home situated in a peaceful residential neighbourhood with ample outdoor space.",
    agent: "Kemi Oladipo",
  },

  {
    id: 9,
    title: "Modern Studio Apartment",
    location: "Wuse 2, Abuja",
    price: 2800000,
    type: "studio",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 1,
    bathrooms: 1,
    area: 48,
    image: "9.jpg",
    amenities: [
      "Security",
      "Parking",
      "Generator",
    ],
    description:
      "Stylish studio apartment ideal for professionals looking for convenient city living.",
    agent: "Grace Peter",
  },

  {
    id: 10,
    title: "Premium 4-Bedroom Apartment",
    location: "Lekki Phase 2, Lagos",
    price: 120000000,
    type: "apartment",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 5,
    area: 310,
    image: "10.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Parking",
      "Security",
      "CCTV",
    ],
    description:
      "Premium four-bedroom apartment in a modern gated development with excellent facilities.",
    agent: "Chinedu Eze",
  },

  {
    id: 11,
    title: "Student-Friendly 2-Bedroom Flat",
    location: "Samonda, Ibadan",
    price: 1800000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 80,
    image: "11.jpg",
    amenities: [
      "Parking",
      "Security",
      "Water Supply",
    ],
    description:
      "Practical two-bedroom apartment located close to major educational institutions and commercial areas.",
    agent: "Femi Ajayi",
  },

  {
    id: 12,
    title: "Elegant 5-Bedroom Residence",
    location: "Asokoro, Abuja",
    price: 280000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 5,
    bathrooms: 6,
    area: 580,
    image: "12.jpg",
    amenities: [
      "Pool",
      "Garden",
      "BQ",
      "Garage",
      "CCTV",
    ],
    description:
      "Elegant detached residence with spacious interiors and premium security features.",
    agent: "Hassan Bello",
  },

  {
    id: 13,
    title: "Compact 2-Bedroom Apartment",
    location: "Surulere, Lagos",
    price: 2500000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 88,
    image: "13.jpg",
    amenities: [
      "Parking",
      "Security",
      "Prepaid Meter",
    ],
    description:
      "Well-maintained apartment in a convenient central Lagos neighbourhood.",
    agent: "Blessing Okoro",
  },

  {
    id: 14,
    title: "Luxury 6-Bedroom Mansion",
    location: "Banana Island, Lagos",
    price: 750000000,
    type: "mansion",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 6,
    bathrooms: 8,
    area: 900,
    image: "14.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Home Cinema",
      "Garden",
      "Garage",
    ],
    description:
      "Exceptional luxury residence featuring expansive living spaces and high-end recreational facilities.",
    agent: "Victor Nwosu",
  },

  {
    id: 15,
    title: "Modern 3-Bedroom Home",
    location: "Rumuola, Port Harcourt",
    price: 55000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 4,
    area: 330,
    image: "15.webp",
    amenities: [
      "Parking",
      "Garden",
      "Security",
      "BQ",
    ],
    description:
      "Modern detached home with spacious living areas and a private garden.",
    agent: "Esther George",
  },

  {
    id: 16,
    title: "Serviced 2-Bedroom Apartment",
    location: "Jabi, Abuja",
    price: 5500000,
    type: "serviced-apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    image: "16.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Security",
      "Generator",
      "Parking",
    ],
    description:
      "Fully serviced apartment offering convenient modern living in a desirable Abuja neighbourhood.",
    agent: "Samuel Yusuf",
  },

  {
    id: 17,
    title: "Affordable 3-Bedroom House",
    location: "Apata, Ibadan",
    price: 38000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 3,
    area: 300,
    image: "17.jpg",
    amenities: [
      "Parking",
      "Garden",
      "Security",
    ],
    description:
      "Affordable family home offering good space and a peaceful residential environment.",
    agent: "Aisha Lawal",
  },

  {
    id: 18,
    title: "Executive 3-Bedroom Apartment",
    location: "Oniru, Lagos",
    price: 8000000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 3,
    bathrooms: 4,
    area: 190,
    image: "18.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Parking",
      "Security",
    ],
    description:
      "Executive apartment close to major business and entertainment districts.",
    agent: "Kelvin Martins",
  },

  {
    id: 19,
    title: "Contemporary 4-Bedroom House",
    location: "Trans Amadi, Port Harcourt",
    price: 95000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 5,
    area: 470,
    image: "19.jpg",
    amenities: [
      "Garage",
      "Garden",
      "BQ",
      "Security",
    ],
    description:
      "Contemporary four-bedroom home with premium finishes and generous outdoor space.",
    agent: "Mercy Isaac",
  },

  {
    id: 20,
    title: "Modern 1-Bedroom Apartment (6 units)",
    location: "Allen Avenue, Lagos",
    price: 3200000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 1,
    bathrooms: 1,
    area: 65,
    image: "20.jpg",
    amenities: [
      "Parking",
      "Security",
      "Generator",
    ],
    description:
      "Modern one-bedroom apartment situated near shops, restaurants and major business areas.",
    agent: "Daniel Okafor",
  },

  {
    id: 21,
    title: "Spacious 4-Bedroom Duplex",
    location: "Oluyole, Ibadan",
    price: 72000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 5,
    area: 420,
    image: "21.jpg",
    amenities: [
      "BQ",
      "Garden",
      "Parking",
      "Security",
    ],
    description:
      "Spacious duplex designed for comfortable family living in a quiet neighbourhood.",
    agent: "Kemi Oladipo",
  },

  {
    id: 22,
    title: "Luxury 3-Bedroom Apartment",
    location: "Ikoyi, Lagos",
    price: 7500000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 3,
    bathrooms: 4,
    area: 210,
    image: "22.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Security",
      "Parking",
    ],
    description:
      "High-end apartment featuring elegant interiors and premium residential facilities.",
    agent: "Amaka Williams",
  },

  {
    id: 23,
    title: "Family 5-Bedroom Duplex",
    location: "Lugbe, Abuja",
    price: 68000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 5,
    bathrooms: 5,
    area: 500,
    image: "23.jpg",
    amenities: [
      "BQ",
      "Garden",
      "Parking",
      "Security",
    ],
    description:
      "Spacious five-bedroom duplex suitable for a large family seeking comfort and privacy.",
    agent: "Ibrahim Musa",
  },

  {
    id: 24,
    title: "Budget 2-Bedroom Apartment",
    location: "Eleyele, Ibadan",
    price: 1500000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 82,
    image: "24.jpg",
    amenities: [
      "Parking",
      "Water Supply",
      "Security",
    ],
    description:
      "Budget-friendly apartment offering comfortable living at an affordable price.",
    agent: "Tolu Adebayo",
  },

  {
    id: 25,
    title: "Premium 4-Bedroom Residence",
    location: "Chevron, Lagos",
    price: 145000000,
    type: "detached-house",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 4,
    bathrooms: 5,
    area: 500,
    image: "25.webp",
    amenities: [
      "Pool",
      "Garden",
      "BQ",
      "Garage",
      "Security",
    ],
    description:
      "Premium family residence with modern architecture and extensive outdoor facilities.",
    agent: "Victor Nwosu",
  },

  {
    id: 26,
    title: "City View 2-Bedroom Apartment",
    location: "GRA, Port Harcourt",
    price: 4000000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    image: "26.jpg",
    amenities: [
      "Parking",
      "Security",
      "Generator",
      "Balcony",
    ],
    description:
      "Comfortable apartment offering convenient city living in an established residential area.",
    agent: "Esther George",
  },

  {
    id: 27,
    title: "Modern 3-Bedroom Duplex",
    location: "Kubwa, Abuja",
    price: 58000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 3,
    bathrooms: 4,
    area: 290,
    image: "27.jpg",
    amenities: [
      "Parking",
      "Garden",
      "Security",
      "BQ",
    ],
    description:
      "Modern duplex offering excellent value with spacious rooms and a private outdoor area.",

  },

  {
    id: 28,
    title: "Cozy 1-Bedroom Apartment(9 units)",
    location: "Ikeja, Lagos",
    price: 1500000,
    type: "apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    image: "28.jpg",
    amenities: [
      "Parking",
      "Security",
      "Water Supply",
    ],
    description:
      "Neat one-bedroom apartment located close to major transport routes and commercial areas.",
    agent: "Michael Adeyemi",
  },

  {
    id: 29,
    title: "Luxury 5-Bedroom Duplex",
    location: "Old GRA, Port Harcourt",
    price: 2100000000,
    type: "duplex",
    purpose: "sale",
    pricePeriod: null,
    bedrooms: 5,
    bathrooms: 6,
    area: 620,
    image: "29.jpg",
    amenities: [
      "Pool",
      "Garden",
      "BQ",
      "Garage",
      "CCTV",
    ],
    description:
      "Luxury family duplex with spacious interiors, premium finishes and excellent security.",
    agent: "Mercy Isaac",
  },

  {
    id: 30,
    title: "Elegant 3-Bedroom Apartment",
    location: "Katampe, Abuja",
    price: 120000000,
    type: "serviced-apartment",
    purpose: "rent",
    pricePeriod: "year",
    bedrooms: 3,
    bathrooms: 3,
    area: 160,
    image: "30.jpg",
    amenities: [
      "Pool",
      "Gym",
      "Parking",
      "Security",
      "Generator",
    ],
    description:
      "Elegant serviced apartment combining modern design, comfort and convenient residential facilities.",
    agent: "Sarah Johnson",
  },
];

export default properties;